### ISSUE TITLE
FAKE  NO TEXTURE

### ISSUE THREAD

**Issue by UnknownSkid** [Love-and-Tolerance/Resource-Pack-Template#1]
THERE IS NO TEXTURES  HOW IM GONNA MAKE A TEXTURE PACK  HOW?

**Comment by SilkRose** [comment]
It's empty for a reason, you don't want to make your pack with all the vanilla textures inside it, this is a bad practice and can cause many issues in the future, if you need help making a pack and finding the default textures, [here's](https://github.com/Love-and-Tolerance/Resource-Pack-Guide) a guide I wrote.
